/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.mail.*;
import javax.mail.internet.*;

/**
 *
 * @author Destockafric
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Login() {
        initComponents();
        this.setTitle("E-leraning ");
        Loginbtn.requestFocusInWindow();
        pack();
        setLocationRelativeTo(null); // center window
        setResizable(false);

    }
    public void sendEmail(String toEmail, String newPassword) {

    final String fromEmail = "elmezouariabdelhadi@gmail.com"; 
    final String fromPassword = "lfqoguspsrrnyjub"; // Gmail App Password

    java.util.Properties props = new java.util.Properties();
    props.put("mail.smtp.host", "smtp.gmail.com");
    props.put("mail.smtp.port", "587");
    props.put("mail.smtp.auth", "true");
    props.put("mail.smtp.starttls.enable", "true");

    javax.mail.Session session = javax.mail.Session.getInstance(props,
        new javax.mail.Authenticator() {
            @Override
            protected javax.mail.PasswordAuthentication getPasswordAuthentication() {
                return new javax.mail.PasswordAuthentication(fromEmail, fromPassword);
            }
        }
    );

    try {
        javax.mail.Message msg = new javax.mail.internet.MimeMessage(session);
        msg.setFrom(new javax.mail.internet.InternetAddress(fromEmail, "E-Learning App"));
        msg.setRecipient(javax.mail.Message.RecipientType.TO,
                new javax.mail.internet.InternetAddress(toEmail));
        msg.setSubject("Password Reset");
        msg.setText("Your new temporary password is: " + newPassword +
                    "\n\nPlease log in and change it after you sign in.");

        javax.mail.Transport.send(msg);

    } catch (Exception e) {
        e.printStackTrace();
    }
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailTxt = new javax.swing.JTextField();
        passTxt = new javax.swing.JPasswordField();
        Loginbtn = new javax.swing.JButton();
        forgotBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1270, 840));
        getContentPane().setLayout(null);

        emailTxt.setBackground(new java.awt.Color(227, 242, 253));
        emailTxt.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 18));
        emailTxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 10));
        // placeholder gray
        java.awt.Color placeholder = new java.awt.Color(150, 150, 150);
        java.awt.Color textColor   = new java.awt.Color(0, 0, 0);

        // initial placeholder
        emailTxt.setText("Enter ur Email");
        emailTxt.setForeground(placeholder);

        // behavior
        emailTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (emailTxt.getText().equals("Enter ur Email")) {
                    emailTxt.setText("");
                    emailTxt.setForeground(textColor);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (emailTxt.getText().trim().isEmpty()) {
                    emailTxt.setText("Enter ur Email");
                    emailTxt.setForeground(placeholder);
                }
            }
        });
        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });
        getContentPane().add(emailTxt);
        emailTxt.setBounds(830, 430, 330, 50);

        passTxt.setBackground(new java.awt.Color(227, 242, 253));
        passTxt.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 10));
        // font
        passTxt.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 18));

        // colors
        java.awt.Color placeholder1 = new java.awt.Color(150, 150, 150);
        java.awt.Color textColor1   = new java.awt.Color(0, 0, 0);

        // initial placeholder
        passTxt.setText("Enter ur Password");
        passTxt.setForeground(placeholder1);
        passTxt.setEchoChar((char)0);

        // behavior
        passTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                String p = String.valueOf(passTxt.getPassword());
                if (p.equals("Enter ur Password")) {
                    passTxt.setText("");
                    passTxt.setForeground(textColor);
                    passTxt.setEchoChar('•');
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                String p = String.valueOf(passTxt.getPassword());
                if (p.trim().isEmpty()) {
                    passTxt.setText("Enter ur Password");
                    passTxt.setForeground(placeholder);
                    passTxt.setEchoChar((char)0);
                }
            }
        });
        getContentPane().add(passTxt);
        passTxt.setBounds(830, 510, 330, 50);

        Loginbtn.setBackground(new java.awt.Color(21, 101, 192));
        Loginbtn.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        Loginbtn.setForeground(new java.awt.Color(255, 255, 255));
        Loginbtn.setText("Login");
        Loginbtn.setBorder(null);
        Loginbtn.setContentAreaFilled(false);
        Loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Loginbtn);
        Loginbtn.setBounds(823, 630, 340, 40);

        forgotBtn.setText("jButton1");
        forgotBtn.setText("Forgot Password?");
        forgotBtn.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 16));
        forgotBtn.setForeground(new java.awt.Color(255, 255, 255));
        forgotBtn.setBorder(null);
        forgotBtn.setContentAreaFilled(false);
        forgotBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotBtnActionPerformed(evt);
            }
        });
        getContentPane().add(forgotBtn);
        forgotBtn.setBounds(790, 690, 200, 29);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/login f7.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 0, 1270, 847);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginbtnActionPerformed
        String email = emailTxt.getText();
        String password = String.valueOf(passTxt.getPassword());
        
        if (email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both email and password");
            return;
        }

        try {
            Connection con = Connexion.Connexion.getConnection();

            String sql = "SELECT * FROM user WHERE email = ? AND password = SHA1(?)";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, email);
            ps.setString(2, password);  

            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Login successful!");
                new Main().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Invalid email or password");
            }

            rs.close();
            ps.close();
            

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Database error");
        }
    
    }//GEN-LAST:event_LoginbtnActionPerformed

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void forgotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotBtnActionPerformed
        String email = emailTxt.getText().trim();

        if (email.equals("Enter ur Email") || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your email first.");
            return;
        }

        try {
            Connection con = Connexion.Connexion.getConnection();

            // Check if email exists
            PreparedStatement ps = con.prepareStatement("SELECT * FROM user WHERE email=?");
            ps.setString(1, email);
            ResultSet rs = ps.executeQuery();

            if (!rs.next()) {
                JOptionPane.showMessageDialog(this, "This email is not registered.");
                return;
            }

            // Generate temporary password
            String tempPass = Long.toHexString(Double.doubleToLongBits(Math.random())).substring(0, 8);

            // Update password using SQL SHA1
            PreparedStatement ps2 = con.prepareStatement(
                "UPDATE user SET password = SHA1(?) WHERE email = ?"
            );
            ps2.setString(1, tempPass);   // plain password
            ps2.setString(2, email);
            ps2.executeUpdate();

            // Send the password email
            sendEmail(email, tempPass);

            JOptionPane.showMessageDialog(this,
                    "A new password has been sent to your email.\nUse it to log in.");

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error resetting password.");
        }
    }//GEN-LAST:event_forgotBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Loginbtn;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JButton forgotBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField passTxt;
    // End of variables declaration//GEN-END:variables
}
