/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import entities.Cours;
import javax.swing.JOptionPane;
import services.CoursService;

/**
 *
 * @author Destockafric
 */
public class UpdateCoursFrame extends javax.swing.JFrame {

    int CoursId;
    CoursService cs=null;
    Main parent;
    /**
     * Creates new form UpdateStudentFrame
     */
    public UpdateCoursFrame(int id,Main parent ) {
        initComponents();
        this.CoursId=id;
        this.parent=parent;
        cs=new CoursService();
        loadToUpdate();
    }
    public void loadToUpdate(){
        Cours c=cs.findById(CoursId);
        categorieTxt.setText(c.getCategorie());
        titleTxt.setText(c.getTitle());
        nbhSpin.setValue(c.getNb_H());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        categorieTxt = new javax.swing.JTextField();
        titleTxt = new javax.swing.JTextField();
        Updatebtn1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nbhSpin = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Add new Cours", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 20), new java.awt.Color(7, 59, 122))); // NOI18N

        categorieTxt.setPreferredSize(new java.awt.Dimension(200, 36));
        categorieTxt.setBackground(new java.awt.Color(255, 255, 255));
        categorieTxt.setForeground(new java.awt.Color(30, 30, 30));
        categorieTxt.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16));

        javax.swing.border.Border normalBorder =
        javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(
                new java.awt.Color(211, 216, 224), // same dark blue as your menu
                2,                              // thickness
                true
            ),
            javax.swing.BorderFactory.createEmptyBorder(8, 10, 8, 10)
        );

        // Hover border (darker gray)
        javax.swing.border.Border hoverBorder =
        javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(
                new java.awt.Color(211, 216, 224), 2, true // inner blue border
            ),
            javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createLineBorder(
                    new java.awt.Color(211, 216, 224), 2, true // outer glow
                ),
                javax.swing.BorderFactory.createEmptyBorder(3, 5, 3, 5)
            )
        );
        // Apply normal border first
        categorieTxt.setBorder(normalBorder);

        // Hover effect
        categorieTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                categorieTxt.setBorder(hoverBorder);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                categorieTxt.setBorder(normalBorder);
            }
        });

        // Placeholder text
        categorieTxt.setText("Enter the categorie");
        categorieTxt.setForeground(new java.awt.Color(150, 150, 150)); // placeholder gray

        categorieTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (categorieTxt.getText().equals("Enter the categorie")) {
                    categorieTxt.setText("");
                    categorieTxt.setForeground(new java.awt.Color(30, 30, 30)); // normal text
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (categorieTxt.getText().trim().isEmpty()) {
                    categorieTxt.setText("Enter the categorie");
                    categorieTxt.setForeground(new java.awt.Color(150, 150, 150)); // placeholder
                }
            }
        });
        categorieTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorieTxtActionPerformed(evt);
            }
        });

        titleTxt.setPreferredSize(new java.awt.Dimension(200, 36));
        titleTxt.setBackground(new java.awt.Color(255, 255, 255));
        titleTxt.setForeground(new java.awt.Color(30, 30, 30));
        titleTxt.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 16));

        // Apply normal border first
        titleTxt.setBorder(normalBorder);

        // Hover effect
        titleTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                categorieTxt.setBorder(hoverBorder);
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                categorieTxt.setBorder(normalBorder);
            }
        });

        // Placeholder text
        titleTxt.setText("Enter the title");
        titleTxt.setForeground(new java.awt.Color(150, 150, 150)); // placeholder gray

        titleTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (titleTxt.getText().equals("Enter the title")) {
                    titleTxt.setText("");
                    titleTxt.setForeground(new java.awt.Color(30, 30, 30)); // normal text
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (titleTxt.getText().trim().isEmpty()) {
                    titleTxt.setText("Enter the title");
                    titleTxt.setForeground(new java.awt.Color(150, 150, 150)); // placeholder
                }
            }
        });
        titleTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTxtActionPerformed(evt);
            }
        });

        Updatebtn1.setBackground(new java.awt.Color(14, 71, 140));
        Updatebtn1.setForeground(new java.awt.Color(255, 255, 255));
        Updatebtn1.setText("Update");
        Updatebtn1.setContentAreaFilled(false);
        Updatebtn1.setOpaque(true);
        Updatebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Updatebtn1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Categorie:");

        jLabel8.setText("Title:");

        jLabel9.setText("Number of Hours:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(titleTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addComponent(categorieTxt)))
                        .addGap(103, 103, 103)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(nbhSpin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Updatebtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(categorieTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Updatebtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nbhSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        // Apply the normal border initially

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(47, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categorieTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorieTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categorieTxtActionPerformed

    private void titleTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTxtActionPerformed

    private void Updatebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Updatebtn1ActionPerformed
        int nbh = (int) nbhSpin.getValue();
        Cours c =new Cours(CoursId ,categorieTxt.getText(),titleTxt.getText(),nbh);
        cs.update(c);
        JOptionPane.showMessageDialog(this, "Cours updated!");
        parent.loadCrs();
        this.dispose();
    }//GEN-LAST:event_Updatebtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Updatebtn1;
    private javax.swing.JTextField categorieTxt;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSpinner nbhSpin;
    private javax.swing.JTextField titleTxt;
    // End of variables declaration//GEN-END:variables
}
